# my_file = open("C:/Users/chani/OneDrive/Documents/Test.txt", 'r+', encoding='UTF-8')  # r+ allow me to add data to file
# #print(my_file)
# a = my_file.read()
# # c = a.replace(" ", ", ")
# # print(c)
# my_file.closed
# my_file2 = open("C:/Users/chani/OneDrive/Documents/Test.txt", 'a', encoding='UTF-8')
# my_file2.write('\n' "david " "cohen " "0532212123 ")

# try:
# #my_file3 = open("C:/Users/chani/OneDrive/Documents/Test5.txt", 'r', encoding='UTF-8')   #exception
#     my_file3 = open("C:/Users/chani/OneDrive/Documents/Test2.txt", 'r', encoding='UTF-8')
#     my_file3.write("123")
# except IOError as ttt:
#     print(ttt)
#     print("Error: cant find file or read data")
# except ValueError:
#     print("value error")
# finally:
#     print("this is the end")
#
# print("we have a problem") # try & exception not stop the running
#

# try:
#     my_file3 = open("C:/Users/chani/OneDrive/Documents/Test2.txt", 'r', encoding='UTF-8')
#     my_file3.write("123")
# finally:
#     print("yes we have a problem")

#debug

x = 10
x = 12
x = 30
print(x)

